# Generated by Django 4.1.3 on 2023-04-04 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song_love',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('artist', models.CharField(blank=True, max_length=150, null=True)),
                ('duration', models.CharField(max_length=10)),
                ('poster', models.CharField(max_length=350)),
                ('mp3_file', models.CharField(max_length=350)),
                ('User_Link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Link_Song_love', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
