# Generated by Django 4.1.3 on 2023-04-06 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_song_name_alter_song_love_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play_list_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('artist', models.CharField(blank=True, max_length=150, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('poster', models.CharField(blank=True, max_length=350, null=True)),
                ('mp3_file', models.CharField(blank=True, max_length=350, null=True)),
                ('id_Song', models.CharField(blank=True, max_length=150, null=True)),
                ('Name_Play_list', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('User_Link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Link_Play_list_add', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Play_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('User_Link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Link_Play_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
