# Generated by Django 4.1.3 on 2023-04-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_play_list_add_play_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play_list',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
