# Generated by Django 4.1.3 on 2023-04-07 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_play_list_add_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Late_song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('artist', models.CharField(blank=True, max_length=150, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('poster', models.CharField(blank=True, max_length=350, null=True)),
                ('mp3_file', models.CharField(blank=True, max_length=350, null=True)),
                ('id_Song', models.CharField(blank=True, max_length=150, null=True)),
                ('User_Link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Link_Late_song', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
