# Generated by Django 4.1.3 on 2023-04-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_late_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play_list_add',
            name='Name_Play_list',
        ),
        migrations.RemoveField(
            model_name='play_list_add',
            name='User_Link',
        ),
    ]
